import { commands } from 'vscode';

/**
 * Seams for {@link revealViewWith} so the reveal ladder can be unit-tested
 * without a workbench.
 */
export interface RevealViewDeps {
  /** Runs a workbench command; rejects when the command is not registered. */
  executeCommand: (command: string) => Promise<unknown>;
  /**
   * Reveals the view through a handle the extension already owns (a resolved
   * `WebviewView`, a `TreeView`, …). Returns false when there is nothing to
   * show yet — a view that has never been on screen has no handle.
   */
  showFromProvider: () => boolean;
  /**
   * Resolves to whether the view ended up on screen. Visibility travels back
   * from the workbench asynchronously, so implementations poll for a moment
   * before giving up. Views we cannot observe report `true`, which stops the
   * ladder after the first step that did not throw.
   */
  waitUntilVisible: () => Promise<boolean>;
  log: (message: string) => void;
}

const VISIBILITY_POLL_INTERVAL_MS = 50;
const VISIBILITY_TIMEOUT_MS = 500;

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Polls `isVisible` until it reports true or {@link VISIBILITY_TIMEOUT_MS}
 * elapses — `WebviewView.visible` is updated by a message from the workbench,
 * so it is still false immediately after the reveal command resolves.
 */
export async function waitUntilVisible(isVisible: () => boolean): Promise<boolean> {
  const attempts = Math.ceil(VISIBILITY_TIMEOUT_MS / VISIBILITY_POLL_INTERVAL_MS);

  for (let attempt = 0; attempt < attempts; attempt++) {
    if (isVisible()) {
      return true;
    }
    await delay(VISIBILITY_POLL_INTERVAL_MS);
  }

  return isVisible();
}

/** Runs one rung of the ladder and reports whether the view is on screen afterwards. */
async function attempt(
  label: string,
  run: () => Promise<unknown>,
  deps: RevealViewDeps
): Promise<boolean> {
  try {
    await run();
  } catch (error) {
    deps.log(`revealView: ${label} failed (${error})`);
    return false;
  }

  const revealed = await deps.waitUntilVisible();
  deps.log(`revealView: ${label} ${revealed ? 'revealed the view' : 'left the view hidden'}`);

  return revealed;
}

/**
 * Reveals `viewId`, escalating until the view is actually on screen.
 *
 * `<viewId>.focus` is generated by the workbench (`ViewsService.
 * registerFocusViewAction`), not contributed by us: it can be missing while the
 * extension updates in place, while its container is relocated, or during a
 * reload race, and even when it is registered it resolves silently without
 * revealing anything if the workbench decides the view is not open-able yet.
 * Either way the click does nothing the user can see, so a single blind attempt
 * is not enough.
 *
 * Opening the view container is *not* a substitute: it restores whichever view
 * was last active there (Worktrees), so on its own it answers a "show me the
 * Stacks view" click with a different view. It is only useful as a step towards
 * the view — hence the retry of the focus action once the container is on
 * screen.
 *
 * Returns whether the view was revealed.
 */
export async function revealViewWith(
  viewId: string,
  viewContainerId: string,
  deps: RevealViewDeps
): Promise<boolean> {
  const focusCommand = `${viewId}.focus`;
  const containerCommand = `workbench.view.extension.${viewContainerId}`;

  // The focus action opens the container *and* expands and focuses the view, so
  // it is the one step that fully answers the click. Execute it blind rather
  // than pre-checking `commands.getCommands()`: the check costs a round trip and
  // a missing entry silently downgrades the click to a fallback that reveals
  // some other view.
  if (await attempt(focusCommand, () => deps.executeCommand(focusCommand), deps)) {
    return true;
  }

  // A view that has been on screen before can be revealed through its own
  // handle, with no workbench command involved.
  if (
    await attempt(
      'provider show',
      async () => {
        if (!deps.showFromProvider()) {
          throw new Error('view has not been resolved yet');
        }
      },
      deps
    )
  ) {
    return true;
  }

  // Last resort: put the container on screen (the focus action is registered as
  // the view descriptor lands in a located container) and ask for the view again.
  if (
    await attempt(
      `${containerCommand} + ${focusCommand}`,
      async () => {
        await deps.executeCommand(containerCommand);
        await deps.executeCommand(focusCommand);
      },
      deps
    )
  ) {
    return true;
  }

  deps.log(`revealView: could not reveal ${viewId}`);

  return false;
}

/**
 * Reveals `viewId`, wired to the real workbench. `isVisible`/`showFromProvider`
 * come from the view's provider when the caller has one; without them the first
 * step that does not throw is taken at its word.
 */
export async function revealView(
  viewId: string,
  viewContainerId: string,
  options: {
    isVisible?: () => boolean;
    showFromProvider?: () => boolean;
    log?: (message: string) => void;
  } = {}
): Promise<boolean> {
  const { isVisible, showFromProvider, log } = options;

  return revealViewWith(viewId, viewContainerId, {
    executeCommand: (command) => Promise.resolve(commands.executeCommand(command)),
    showFromProvider: showFromProvider ?? (() => false),
    waitUntilVisible: isVisible ? () => waitUntilVisible(isVisible) : () => Promise.resolve(true),
    log: log ?? (() => undefined),
  });
}
