name: Build and Test

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
  #  branches: ['**'] # Triggers on push to any branch
  # pull_request:
  #   branches: ['main'] # Also run on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run build-all
        run: yarn build-all
